services:

  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis

  admin:
    build:
      context: .
      dockerfile: admin.Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "127.0.0.1:${ADMIN_PORT}:8000"

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    command:
      - "redis-server"
      - "--appendonly"
      - "yes"
    volumes:
      - redis_data:/data


volumes:
  redis_data: